services:
  db:
    container_name: postgresql-Fish-Project
    image: postgres:latest
    environment:
      POSTGRES_USER: tanphan
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5132:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db: