spring.application.name=Project_Fish_Final
spring.datasource.url= jdbc:postgresql://localhost:5132/fishing_data
spring.datasource.password= 123
spring.datasource.username= tanphan
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver